blueprint:
  name: AduroSmart Remote scene controller
  description: Blueprint for the AduroSmart Remote scene controller
  domain: automation
  input:
    mqtt_device:
      name: AduroSmart device
      description: Select the device
      selector:
        device:
          integration: mqtt
          manufacturer: AduroSmart
          model: Remote scene controller
    command_toggle:
      name: Command for pressing power button
      description: Action to perform on pressing power button - command toggle
      default: []
      selector:
        action: {}
    command_recall_253:
      name: Command for pressing 1
      description: Action to perform on pressing 1 button - command recall_253
      default: []
      selector:
        action: {}
    command_recall_254:
      name: Command for pressing 2
      description: Action to perform on pressing 2 button - command recall_254
      default: []
      selector:
        action: {}
    command_recall_255:
      name: Command for pressing 3
      description: Action to perform on pressing 3 button - command recall_255
      default: []
      selector:
        action: {}

trigger:
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: toggle
    id: toggle
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: recall_253
    id: recall_253
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: recall_254
    id: recall_254
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: recall_255
    id: recall_255

action:
  - choose:
      - conditions:
          - condition: trigger
            id: toggle
        sequence: !input command_toggle
      - conditions:
          - condition: trigger
            id: recall_253
        sequence: !input command_recall_253
      - conditions:
          - condition: trigger
            id: recall_254
        sequence: !input command_recall_254
      - conditions:
          - condition: trigger
            id: recall_255
        sequence: !input command_recall_255
